xtpm2-password: get encrypted disk from /etc/crypttab

diff --git a/xtpm2-password b/xtpm2-password
--- a/xtpm2-password
+++ b/xtpm2-password
@@ -51,10 +51,18 @@ fi
 OLD_PWD=${1}
 NEW_PWD=${2}
 
+if [ "x${CRYPTDISK}" == "x" ]; then
+	CRYPTDISK=/dev/disk/by-uuid/$(grep luks /etc/crypttab|cut -d ' ' -f 2|cut -d '=' -f 2 2>/dev/null)
+	if [ ! -b ${CRYPTDISK} ]; then
+		echo "Cannot find encrypted disk from crypttab"
+		exit 1
+	fi
+fi
+
 # change password in luks from OLD_PWD to NEW_PWD
 # NOTE: newPassword.key is on encrypted partition
-echo $NEW_PWD > newPassword.key
-echo -n $OLD_PWD | cryptsetup luksChangeKey test.img newPassword.key
+echo -n $NEW_PWD > newPassword.key
+echo -n $OLD_PWD | cryptsetup luksChangeKey ${CRYPTDISK} newPassword.key
 rm newPassword.key
 
 # set TPM
